set(PROJECT_VERSION_MAJOR 4)
set(PROJECT_VERSION_MINOR 2)
set(PROJECT_VERSION_PATCH 5)

set(VERSIONINFO_OUTPUT_RC "${CMAKE_CURRENT_LIST_DIR}/build/LocalGen.rc")

message(STATUS "Version: ${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH}")
message(STATUS "Resource file: ${VERSIONINFO_OUTPUT_RC}")

string(TIMESTAMP CURRENT_YEAR "%Y")

set(BUILD_NUMBER_FILE "${CMAKE_CURRENT_LIST_DIR}/build_number.txt")
file(READ ${BUILD_NUMBER_FILE} BUILD_NUMBER)
string(STRIP ${BUILD_NUMBER} BUILD_NUMBER)
math(EXPR BUILD_NUMBER "${BUILD_NUMBER} + 1")
file(WRITE ${BUILD_NUMBER_FILE} "${BUILD_NUMBER}\n")

set(BUILD_NUMBER ${BUILD_NUMBER})

configure_file("${CMAKE_CURRENT_LIST_DIR}/LocalGen.rc.in" "${VERSIONINFO_OUTPUT_RC}")
configure_file("${CMAKE_CURRENT_LIST_DIR}/verinfo.h.in" "${CMAKE_CURRENT_LIST_DIR}/verinfo.h")
