// Copyright (C) 2026 SZXC Work Group
// SPDX-License-Identifier: GPL-3.0-or-later

#pragma once

/**
 * @file board.hpp
 *
 * LocalGen Module: core
 *
 * Map Boards
 *
 * Container of maps.
 */

#include <cassert>
#include <random>
#include <string>
#include <unordered_map>
#include <vector>

#include "move.hpp"
#include "tile.hpp"
#include "utils.hpp"

/// A player's view of the board, generated by `board.view(player)`.
struct BoardView {
    pos_t row, col;
    std::vector<TileView> tiles;

    inline TileView& tileAt(pos_t x, pos_t y) {
        return tiles[x * (col + 2) + y];
    };
    inline const TileView& tileAt(pos_t x, pos_t y) const {
        return tiles[x * (col + 2) + y];
    };

    inline TileView& tileAt(Coord pos) { return tileAt(pos.x, pos.y); };
    inline const TileView& tileAt(Coord pos) const {
        return tileAt(pos.x, pos.y);
    };
};

/// Game map board.
class Board {
   public:
    pos_t row = 0, col = 0;
    std::vector<Tile> tiles;

    inline Tile& tileAt(pos_t x, pos_t y) { return tiles[x * (col + 2) + y]; };
    inline const Tile& tileAt(pos_t x, pos_t y) const {
        return tiles[x * (col + 2) + y];
    };
    inline Tile& tileAt(Coord pos) { return tileAt(pos.x, pos.y); };
    inline const Tile& tileAt(Coord pos) const { return tileAt(pos.x, pos.y); };

    void setWidth(pos_t _col) {
        assert(_col >= 0);
        col = _col;
        tiles.resize((row + 2) * (col + 2));
        visionCache.clear();
    }

    void setHeight(pos_t _row) {
        assert(_row >= 0);
        row = _row;
        tiles.resize((row + 2) * (col + 2));
        visionCache.clear();
    }

   public:
    inline bool isValidPos(pos_t x, pos_t y) const {
        return x >= 1 && x <= row && y >= 1 && y <= col;
    }
    inline bool isValidPos(Coord pos) const { return isValidPos(pos.x, pos.y); }
    inline bool isInvalidPos(pos_t x, pos_t y) const {
        return !isValidPos(x, y);
    }
    inline bool isInvalidPos(Coord pos) const { return !isValidPos(pos); }

   public:
    inline int getWidth() const { return col; }
    inline int getHeight() const { return row; }

   public:
    Board() = default;
    Board(pos_t _row, pos_t _col) : row(_row), col(_col) {
        assert(row >= 0 && col >= 0);
        // board index starts at 1.
        // padding dummy tiles around for safety and convenience issues:
        tiles.resize((_row + 2) * (_col + 2));
    }

    /// Vision system.
   protected:
    /// visionCache[n][x][y], flattened into 1D for better performance.
    std::vector<uint8_t> visionCache;

   public:
    /// Update the vision cache. Must be called after a board update.
    void updateVisionCache() {
        const pos_t C = col + 2, RC = (row + 2) * C;
        if (visionCache.empty()) {
            index_t maxPlayer = 0;
            for (const auto& tile : tiles) {
                if (tile.occupier > maxPlayer) maxPlayer = tile.occupier;
            }
            visionCache.resize((maxPlayer + 1) * RC, false);
        } else {
            visionCache.assign(visionCache.size(), false);
        }

        static const std::pair<int, int> dirs[4] = {
            {-1, 0}, {1, 0}, {0, -1}, {0, 1}};
        auto assignLookoutVision = [&](pos_t x, pos_t y) -> void {
            // 1. Find lookout occupier
            index_t occupier = -1;
            army_t maxArmy = 0;
            for (auto [dx, dy] : dirs) {
                const Tile& tile = tileAt(x + dx, y + dy);
                if (tile.army > maxArmy && tile.occupier != -1) {
                    occupier = tile.occupier;
                    maxArmy = tile.army;
                }
            }
            if (occupier == -1) return;

            // 2. Assign 5x5 lookout vision
            for (pos_t i = std::max(x - 2, 1), r = std::min(x + 2, row); i <= r;
                 ++i) {
                for (pos_t j = std::max(y - 2, 1), c = std::min(y + 2, col);
                     j <= c; ++j) {
                    visionCache[occupier * RC + i * C + j] = true;
                }
            }
        };

        auto assignObservatoryVision = [&](pos_t x, pos_t y) -> void {
            for (auto [dx, dy] : dirs) {
                index_t player = tileAt(x - dx, y - dy).occupier;
                if (player == -1) continue;
                int base = player * RC + x * C + y;
                int step = dx * C + dy;
                pos_t nx = x, ny = y;
                for (int i = 0; i < 8; ++i) {
                    nx += dx, ny += dy, base += step;
                    if (isInvalidPos(nx, ny)) break;
                    visionCache[base] = true;
                }
            }
        };

        const index_t numPlayers = visionCache.size() / RC;
        for (pos_t x = 1; x <= row; ++x) {
            for (pos_t y = 1; y <= col; ++y) {
                const Tile& tile = tileAt(x, y);
                if (tile.lit) {
                    size_t base = x * C + y;
                    for (index_t player = 0; player < numPlayers;
                         ++player, base += RC)
                        visionCache[base] = true;
                }
                index_t player = tile.occupier;
                if (player == -1) {
                    tile_type_e type = tile.type;
                    if (type == TILE_LOOKOUT)
                        assignLookoutVision(x, y);
                    else if (type == TILE_OBSERVATORY)
                        assignObservatoryVision(x, y);
                } else {
                    size_t base = player * RC + x * C + y;
                    for (size_t rbase : {base - C, base, base + C}) {
                        visionCache[rbase - 1] = true;
                        visionCache[rbase] = true;
                        visionCache[rbase + 1] = true;
                    }
                }
            }
        }
    }

    /// Tile visibility check for a player.
    inline bool visible(pos_t x, pos_t y, index_t player) const {
        if (isInvalidPos(x, y)) return false;
        const pos_t C = col + 2, RC = (row + 2) * C;
        return visionCache[player * RC + x * C + y];
    };

    /// Same as above, but using %Coord.
    inline bool visible(const Coord& pos, index_t player) const {
        return visible(pos.x, pos.y, player);
    };

   public:
    bool available(index_t player, Move move) const {
        MoveType type = move.type;
        if (type == MoveType::EMPTY) return false;
        if (type == MoveType::SURRENDER) return true;
        assert(type == MoveType::MOVE_ARMY);

        const Coord &from = move.from, &to = move.to;

        // coordinate validity check
        if (isInvalidPos(from) || isInvalidPos(to)) return false;

        // adjacency check (orthogonal 4-neighborhood)
        if (std::abs(from.x - to.x) + std::abs(from.y - to.y) != 1)
            return false;

        // from tile availability check
        const Tile& fromTile = tileAt(from);
        if (fromTile.occupier != player || fromTile.army <= 1) return false;

        // to tile availability check
        if (isImpassableTile(tileAt(to).type)) return false;

        // all passed, available move
        return true;
    };

   public:
    void update(bool increaseAllArmy = false) {
        for (auto& tile : tiles) {
            if (tile.occupier == -1) continue;
            switch (tile.type) {
                case TILE_DESERT:           continue;
                case TILE_CITY:
                case TILE_GENERAL:
                case TILE_CAPTURED_GENERAL: ++tile.army; break;
                case TILE_SWAMP:
                    if (tile.army > 0 && --tile.army == 0) {
                        tile.occupier = -1;
                        continue;
                    }
                    break;
                default: break;
            }
            if (increaseAllArmy) ++tile.army;
        }
    }

   public:
    void view(index_t player, BoardView& boardView) const {
        boardView.row = row, boardView.col = col;
        auto& tileViews = boardView.tiles;
        tileViews.resize((row + 2) * (col + 2));
        for (pos_t i = 1; i <= row; ++i) {
            for (pos_t j = 1; j <= col; ++j) {
                boardView.tileAt(i, j).updateFrom(tileAt(i, j),
                                                  visible(i, j, player));
            }
        }
    }

    BoardView view(index_t player) const {
        BoardView boardView;
        view(player, boardView);
        return boardView;
    }

    BoardView fullView() const {
        BoardView boardView;
        auto& tileViews = boardView.tiles;
        boardView.row = row, boardView.col = col;
        tileViews.resize((row + 2) * (col + 2));
        for (pos_t i = 1; i <= row; ++i) {
            for (pos_t j = 1; j <= col; ++j) {
                boardView.tileAt(i, j).updateFrom(tileAt(i, j), true);
            }
        }
        return boardView;
    }

    inline TileView view(index_t player, pos_t row, pos_t col) const {
        return TileView(tileAt(row, col), visible(row, col, player));
    }
    inline TileView view(index_t player, Coord pos) const {
        return TileView(tileAt(pos), visible(pos, player));
    };

   public:
    static Board generate(int width, int height, int spawnCount,
                          std::mt19937::result_type seed,
                          bool placeSwamp = false, bool placeLookout = false,
                          bool placeObservatory = false,
                          double mountainDensity = 0.3);
};

#include "mapgen.hpp"
