name: Qt Build

on:
  push:
    branches: [master]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: [master]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux (GCC)
            os: ubuntu-latest
            qt_arch: linux_gcc_64
            qt_tools: ''

          - name: macOS (Clang)
            os: macos-latest
            qt_arch: clang_64
            qt_tools: ''

          - name: Windows (MSVC)
            os: windows-latest
            qt_arch: win64_msvc2022_64
            qt_tools: ''

          - name: Windows (MinGW)
            os: windows-latest
            qt_arch: win64_mingw
            qt_tools: 'tools_mingw1310'

          - name: Windows (LLVM)
            os: windows-latest
            qt_arch: win64_llvm_mingw
            qt_tools: 'tools_llvm_mingw1706'

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.8.3
          arch: ${{ matrix.qt_arch }}
          tools: ${{ matrix.qt_tools }}
          cache: true

      - name: Setup MSVC
        if: contains(matrix.qt_arch, 'msvc')
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build
        shell: bash
        run: |
          cmake -B build -S . -G Ninja -DCMAKE_TOOLCHAIN_FILE=$QT_ROOT_DIR/lib/cmake/Qt6/qt.toolchain.cmake
          cmake --build build -j4 --config Release
