name: Qt Build

on:
  push:
    branches: [master]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: [master]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux (GCC)
            os: ubuntu-latest
            qt_arch: linux_gcc_64
            qt_tools: ''

          - name: macOS (Clang)
            os: macos-latest
            qt_arch: clang_64
            qt_tools: ''

          - name: Windows (MSVC)
            os: windows-latest
            qt_arch: win64_msvc2022_64
            qt_tools: ''

          - name: Windows (MinGW)
            os: windows-latest
            qt_arch: win64_mingw
            qt_tools: 'tools_mingw1310'

          - name: Windows (LLVM)
            os: windows-latest
            qt_arch: win64_llvm_mingw
            qt_tools: 'tools_llvm_mingw1706'

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.8.3
          arch: ${{ matrix.qt_arch }}
          tools: ${{ matrix.qt_tools }}
          modules: qtcharts
          cache: true

      - name: Setup MSVC
        if: contains(matrix.qt_arch, 'msvc')
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build
        shell: bash
        run: |
          cmake -B build -S . -G "Ninja Multi-Config" -DCMAKE_TOOLCHAIN_FILE=$QT_ROOT_DIR/lib/cmake/Qt6/qt.toolchain.cmake
          cmake --build build --config Release

      - name: Deploy and Package
        if: matrix.os != 'ubuntu-latest'
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            mkdir -p deploy
            cp build/Release/LocalGen-new.exe deploy/
            if [[ "${{ matrix.qt_arch }}" == *"llvm"* ]]; then
              windeployqt --no-compiler-runtime deploy/*.exe
              ls $QT_ROOT_DIR/bin
              COMPILER_BIN="$(dirname "$(which clang++)")"
              cp "$COMPILER_BIN/libc++.dll" deploy/
              cp "$COMPILER_BIN/libunwind.dll" deploy/
              cp "$COMPILER_BIN/libwinpthread-1.dll" deploy/
            else
              windeployqt --compiler-runtime deploy/*.exe
            fi
            7z a -tzip -mx=9 "${{ matrix.name }}.zip" ./deploy/*
          elif [ "$RUNNER_OS" == "macOS" ]; then
            macdeployqt build/Release/LocalGen-new.app
            cd build/Release
            env GZIP=-9 tar -czvf "../../${{ matrix.name }}.tar.gz" LocalGen-new.app
          fi

      - name: Upload Artifact
        if: matrix.os != 'ubuntu-latest'
        uses: actions/upload-artifact@v7
        with:
          path: |
            *.zip
            *.tar.gz
          compression-level: 0
          archive: false
          if-no-files-found: error
